version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    #ports: 
      #- "6432:5432"  
  web: &web
    build:
      context: .
      args:
        INSTALL_DEPENDENCIES: vim curl htop
        BUNDLE_INSTALL_ARGS: --jobs 10 --retry=3
    #image: rails5-docker-heroku
    command: bundle exec puma -C config/puma.rb 
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL} 
